### ISSUE TITLE
Issue with markdown-it-adobe-plugin usage

### ISSUE THREAD

**Issue by varunutreja** [AdobeDocs/adobe-markdown-authoring#59]
Thanks for the separate markdown-it-adobe-plugin implementation. 
But when I'm using that in my code I'm getting following error. 
Seems like markdown-it-adobe-plugin.js maybe not exporting apply method according to markdown-it plugin conventions. Could you please check.

**Here is what I'm using it like:** 
const MarkdownIt = require('markdown-it'); // version "^13.0.1"
const adobePlugin = require('./markdown-it-adobe-plugin.js'); 

// Initialize MarkdownIt instance with desired options
const md = new MarkdownIt({
  html: true,
});

// Using custom plugin (assuming it's in markdown-it-adobe-plugin.js)
md.use(adobePlugin);

**Here is what error looks like:**
/Users/utreja/workspace/preview-service/node_modules/markdown-it/lib/index.js:497
  plugin.apply(plugin, args);
         ^

TypeError: plugin.apply is not a function
    at MarkdownIt.use (/Users/utreja/workspace/preview-service/node_modules/markdown-it/lib/index.js:497:10)

**Comment by geverit4** [comment]
There were three problems that were fixed with this PR. 

1) The plugin is written to be compatible with both CommonJS (require) and ESM (import) module semantics.  In order for this to work from a CommonJS script, you must append **.default** to the require so that it can find the plugin entry point. 

   Before: 
`const adobePlugin = require('../../releases/markdown-it-adobe-plugin.js');`

   After: 
`const adobePlugin = require('../../releases/markdown-it-adobe-plugin.js').default;`

2) The plugin required a root path as the first argument to the use() method, or else references to relative files like !INCLUDE tags would not be able to locate the files.  Here is how it is called in the extension itself: 

   `md = adobeMarkdownPlugin(md, getRootFolder()?.uri.path || extensionPath);`

   The test script was calling it without the path: 

   `md.use(adobePlugin);`

   The correct approach would be to append a root directory so that tags can find relative paths.  

   `md.use(adobePlugin, 'fixtures')`

3) Given that the omission of the root path only affects one tag that is infrequently used, it makes no sense to catastrophically fail if it is omitted.  Therefore, it is now optional, but you will get a warning on the console if you omit it: 

   A new test script.  Adjust the plugin path to match your environment. 
```
const MarkdownIt = require('markdown-it');
const adobePlugin = require('../../releases/markdown-it-adobe-plugin.js').default;

const md = new MarkdownIt({ html: true });

md.use(adobePlugin); // Simplified plugin for testing

console.log(md.render('# Markdown with Adobe Plugin'));
```

   Emits this output to the console: 

```
Warning: includeFileParts was called without a valid rootDir. The !INCLUDE tag not work as expected.
markdown-it-adobe-plugin.js:1
<h1>Markdown with Adobe Plugin</h1>
```

**Comment by varunutreja** [comment]
Thanks @geverit4 for the detailed illustration. 
As suggested in point #2, I would like to include the root path so that I can support !INCLUDE tags(we already have a bug reported for this). 
So, in the below code, I have a questions in comments:

_const adobePlugin = require('../../releases/markdown-it-adobe-plugin.js').default;_
_md = adobeMarkdownPlugin(md, getRootFolder()?.uri.path || extensionPath);_   //what is adobeMarkdownPlugin here
_md.use(adobePlugin, 'fixtures')_  // didn't undestand 2nd arg in use method i.e. 'fixtures'. I should be using alone this line or use above line as well?

**Comment by geverit4** [comment]
In the example:

`md = adobeMarkdownPlugin(md, getRootFolder()?.uri.path || extensionPath); `

The Markdown Extension runs in the context of VSCode, which has its own notion of workspaces and folders.  Therefore, getRootFolder() uses the VSCode API to try to figure out what is the root folder of the current file under edit. In the case of the plugin being called from outside the context of a VSCode extension, then getRootFolder and extensionPath are not defined so you have to provide the root path that the !INCLUDE tag can use to find any include files.  The "fixtures" root in the example I provided happens to be the root path of our test documents. The !INCLUDE directive will look in ./fixtures/help/_includes for include files.  Since !INCLUDE is Adobe proprietary, it always looks in <doc_root>/help/_includes for include files.  

`md.use(adobePlugin, 'fixtures') // didn't undestand 2nd arg in use method i.e. 'fixtures'. I should be using alone this line or use above line as well?`

So, in your case 'fixtures' might be '.' or some other relative path that has a help/_includes folder in it.
