### ISSUE TITLE
Add Toggle Shade Box to shortcuts

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#6]
If a writer selects Toggle Shade Box as a shortcut, we would:

* Add `>[!BEGINSHADEBOX]` and `>[!ENDSHADEBOX]` on separate lines if no text is selected.
* Wrap selected text with `>[!BEGINSHADEBOX]` and `>[!ENDSHADEBOX]` on their own lines above and below selection.

https://experienceleague.adobe.com/docs/authoring-guide-exl/using/markdown/syntax-style-guide.html?lang=en#shade-boxes

**Comment by bbringhu** [comment]
@geverit4 - Minor issue, but when I select text and choose Toggle Shadebox like this:

![Screenshot 2023-04-12 at 1 07 04 PM](https://user-images.githubusercontent.com/6193209/231572580-93163910-2deb-44bd-be14-57a358d52cd5.png)

The line spacing of the end syntax is off:

![Screenshot 2023-04-12 at 1 08 28 PM](https://user-images.githubusercontent.com/6193209/231572880-e872caef-407f-4235-8660-6d075930cec7.png)

You're adding an extra line before ENDSHADEBOX and removing a blank line after, which can cause a validation error if it precedes a heading, note, or code block.

**Comment by geverit4** [comment]
This was one of the more pernicious bugs.  We have automated testing for all of these, but to deal with this kind of markdown construct is not really supported in the original code that we forked that handles GFM.  I had been wanting to make it more flexible so that you could actually "toggle" the shadebox tabs and have it behave intuitively.  This was my opportunity.  

The shadebox shortcut is now much smarter.   It will detect where your cursor is and look up and down for existing >[!SHADEBOX] tags.  If it finds them, it will remove them.  If it doesn't find them, it will select the current paragraph and surround it.  
 
![Screenshot 2023-04-13 at 10 54 02 PM](https://user-images.githubusercontent.com/1187616/231930540-51e68088-c799-4563-92f4-52c8d23f2dfb.png)

![Screenshot 2023-04-13 at 10 54 42 PM](https://user-images.githubusercontent.com/1187616/231930550-0e4a67cc-d397-4d04-a4de-b526b66d5a14.png)

**Comment by bbringhu** [comment]
Confirmed fixed in 2.0.5
